version: "3.8"
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: api_c
    networks:
      - webnet
    restart: always
  client:
    build: ./client
    networks:
      - webnet
    container_name: client_c
    ports:
      - "3000:3000"
    expose:
      - "3000"
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    networks:
      - webnet
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  nginx:
    image: nginx
    networks:
      - webnet
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports: 
      - "4000:80"
    depends_on:
      - api
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  webnet:
volumes:
  my-db: